apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: queue-monitor-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-secret-store
  refreshInterval: 1h
  data:
    - secretKey: NOTIFICATION_TELEGRAM_BOT_TOKEN
      remoteRef:
        key: /telegram/NOTIFICATION_TELEGRAM_BOT_TOKEN
    - secretKey: NOTIFICATION_TELEGRAM_BROADCAST_CHANNEL_NAME
      remoteRef:
        key: /telegram/NOTIFICATION_TELEGRAM_BROADCAST_CHANNEL_NAME