apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: queue-monitor
  name: queue-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-monitor
  strategy: 
    type: Recreate # it ensures that monitors will not start sending the same status updates in parallel
  template:
    metadata:
      labels:
        app: queue-monitor
    spec:
      containers:
      - image: acrduwshared.azurecr.io/queue-monitor:0.4.1
        name: queue-monitor
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: USE_TELEGRAM_NOTIFICATIONS
          value: "true"
        - name: STATE_REDIS_CONNECTION_STRING
          value: "redis://localhost:6379/0"
        - name: STATUS_CHECK_INTERVAL_SECONDS
          value: "300"
        - name: NOTIFICATION_TELEGRAM_BOT_TOKEN
          value: "7442293468:AAGt4PGhShMtQPmKYJGlFV49W5EUEewLR7s"
        - name: NOTIFICATION_TELEGRAM_BROADCAST_CHANNEL_NAME
          value: "K6Afqk8DkwD"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi