apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: queue-monitor
  name: queue-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-monitor
  strategy: 
    type: Recreate # it ensures that monitors will not start sending the same status updates in parallel when the deployment is updated
  template:
    metadata:
      labels:
        app: queue-monitor
    spec:
      containers:
      - image: acrduwshared.azurecr.io/queue-monitor:1.0.0
        name: queue-monitor
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: USE_TELEGRAM_NOTIFICATIONS
          value: "true"
        - name: STATE_REDIS_CONNECTION_STRING
          value: "redis://redis-service:6379/0"
        - name: STATUS_CHECK_INTERVAL_SECONDS
          value: "30"
        - name: NOTIFICATION_TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: queue-monitor-external-secret
              key: NOTIFICATION_TELEGRAM_BOT_TOKEN
        - name: NOTIFICATION_TELEGRAM_BROADCAST_CHANNEL_NAME
          valueFrom:
            secretKeyRef:
              name: queue-monitor-external-secret
              key: NOTIFICATION_TELEGRAM_BROADCAST_CHANNEL_NAME
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi